name: Build - Testing

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: nuget restore src/betterlauncher-nextgen/betterlauncher-nextgen.sln

    - name: Build project
      run: msbuild.exe /t:build /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath="bin/Release/" src/betterlauncher-nextgen/betterlauncher-nextgen.csproj

    - name: Test directory - src/betterlauncher-nextgen/bin/release
      run: dir src/betterlauncher-nextgen/bin/Release/

    - name: Get file size
      id: get_file_size
      run: |
        $size = (Get-ChildItem -Path "src/betterlauncher-nextgen/bin/Release/betterlauncher-nextgen.exe" | Measure-Object -Property Length -Sum).Sum / 1KB
        echo "::set-output name=size_kb::$size"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BetterLauncher_${{ github.run_id }}_${{ steps.get_file_size.outputs.size_kb }}kb
        path: src/betterlauncher-nextgen/bin/Release/betterlauncher-nextgen.exe
