name: Build - round 2.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: nuget restore src/betterlauncher-cs.sln

    - name: Build project
      run: msbuild.exe /t:build /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath="src/bin/Release/" src/betterlauncher-cs.csproj

    - name: Test directory?
      run: dir src

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BetterLauncher_${{ github.run_id }}_${{ github.sha }}
        path: src/bin/Release/*
